[package]
name = "localtunnel-client"
version = "0.2.0"
edition.workspace = true
description = "A client to connect with localtunnel server."
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12", features = ["json"], default-features = false }
serde = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
socket2 = { workspace = true }
snowstorm = "0.4"
hex = "0.4"

[features]
default = ["reqwest/default"]
rustls-tls = ["reqwest/rustls-tls"]
